on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '30 3 * * 2'

name: CI

jobs:
  test:
    name: run tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest, ubuntu-20.04]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.62.1 stable
      - name: Build with default features
        run: cargo build
      - name: Build with logging and webpki roots
        run: cargo build --features logging,webpki-roots --no-default-features
      - name: Run tests
        run: cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: dtolnay/rust-toolchain@stable
         with:
           toolchain: 1.62.1 stable
       - name: run clippy lints
         run: cargo clippy --features logging

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.62.1 stable
      - name: run rustfmt
        run: cargo fmt --all -- --check

  docs:
    name: build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.4'
      - name: Build
        run: cargo build
      - name: Ensure that docs can be built
        run: cd docs && mdbook build
      - name: Generate usage string
        run: cargo run -- --help > docs/src/usage-actual.txt
      - name: Ensure that usage string is up to date
        run: diff docs/src/usage{,-actual}.txt
